### Get all users
GET http://localhost:5192/api/users
Accept: application/json

### Get a user by ID
GET http://localhost:5192/api/users/3
Accept: application/json

### Create a new user
POST http://localhost:5192/api/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Update a user
PUT http://localhost:5192/api/users/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "newpassword456"
}

### Delete a user
DELETE http://localhost:5192/api/users/1
